In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer


from xgboost import XGBClassifier
from xgboost import plot_importance

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/raw_postpro.csv')

In [3]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
df1 = df.apply(le.fit_transform)

X = df1[['Subject', 'key2' , "Assembly", '출고운반선', '견적화폐', '발주처']]
y = df1["leadtime"]
# X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=40, shuffle=True, test_size=0.2)

In [5]:
# df["Subject"]+ ' ' + df['key2']  + ' '   + df['Assembly'] + ' '  + df['출고운반선']+  ' ' + df['견적화폐']  +  ' ' + df['발주처'] 
z = df['leadtime']

In [6]:
z.unique()

array([194,  59,  61, 212, 220,  80, 100,  13, 117,  96,   2, 156,  72,
        25,  49,  56,  48,  28,   6,  32,  62,  29,  44,  68,  18,  14,
        92,  81,  34,  42,  75,  78,  30,  93,  69,  41,  50,  37,  21,
       267,  87,  15, 155,  23, 112,  26,  11,  53, 122,  79,  65,  55,
       105, 152,  63,  99,  98,  45,  17,  52, 108,  86,  22, 139,  10,
         0,  43,  12,   8,  16,  20, 107,  77, 120, 145, 184,  85,  35,
       116, 146, 121,  31, 125,  76, 289,  89,   5, 305,  51, 102, 159,
        54, 104,  94,  71, 157,  24,  39, 123,   7, 195,  84,  36, 171,
       129, 309,  74, 183, 131, 150,  57,  27, 106, 133, 383, 315, 283,
       228, 180, 110, 101, 172,  46,  40,   1,   9, 276, 119, 163,  66,
        58,  90,   3, 113, 147, 218, 199,  38,  64,  67, 202, 132, 168,
       111, 161, 357, 115, 216,  47, 208, 282, 272, 178,  97, 141,  70,
       204, 268, 247,  83, 361, 345, 641, 138, 271, 170, 109, 241,  88,
       127, 423, 148,  82, 415, 189,  73, 211, 103, 164, 188, 33

In [9]:
df['leadtime'][:30]

0     194
1      59
2      61
3     212
4     220
5      80
6     100
7      13
8     117
9      96
10      2
11    156
12     72
13     25
14     49
15     49
16     49
17     49
18     56
19     48
20     56
21     56
22     28
23      6
24     56
25     48
26     56
27     48
28      6
29      6
Name: leadtime, dtype: int64

In [10]:
y[:30]

0     190
1      59
2      61
3     203
4     207
5      80
6     100
7      13
8     117
9      96
10      2
11    156
12     72
13     25
14     49
15     49
16     49
17     49
18     56
19     48
20     56
21     56
22     28
23      6
24     56
25     48
26     56
27     48
28      6
29      6
Name: leadtime, dtype: int64

In [11]:
sorted_df_y = y.sort_values( ascending=True)
sorted_df_y.unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
sorted_df_z = z.sort_values( ascending=True)
sorted_df_z.unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       170, 171, 172, 174, 175, 176, 178, 179, 180, 181, 182, 18

In [13]:
y.unique().shape

(273,)

In [52]:
!pip install imblearn

                                              0.0/226.0 kB ? eta -:--:--
     -------------------------------------  225.3/226.0 kB 6.9 MB/s eta 0:00:01
     -------------------------------------- 226.0/226.0 kB 7.0 MB/s eta 0:00:00


In [54]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE

# 실제 데이터의 클래스 범위 확인
actual_classes = y.unique()
num_classes = len(actual_classes)


# 학습 데이터와 테스트 데이터 분리 (클래스 분포 유지)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# SMOTE를 사용하여 데이터 오버샘플링
smote = SMOTE()
X_train_oversampled, y_train_oversampled = smote.fit_resample(X_train, y_train)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

# 특정 y(leadtime) 값의 데이터가 너무 적어서 오버샘플링으로 늘림

In [14]:
from imblearn.over_sampling import RandomOverSampler

# 실제 데이터의 클래스 범위 확인
actual_classes = y.unique()
num_classes = len(actual_classes)

# RandomOverSampler를 사용하여 데이터 오버샘플링
ros = RandomOverSampler(random_state=42)
X_oversampled, y_oversampled = ros.fit_resample(X, y)

# 오버샘플링 후의 클래스 범위 확인
oversampled_classes = y_oversampled.unique()
num_oversampled_classes = len(oversampled_classes)
oversampled_classes, num_oversampled_classes

(array([190,  59,  61, 203, 207,  80, 100,  13, 117,  96,   2, 156,  72,
         25,  49,  56,  48,  28,   6,  32,  62,  29,  44,  68,  18,  14,
         92,  81,  34,  42,  75,  78,  30,  93,  69,  41,  50,  37,  21,
        227,  87,  15, 155,  23, 112,  26,  11,  53, 122,  79,  65,  55,
        105, 152,  63,  99,  98,  45,  17,  52, 108,  86,  22, 139,  10,
          0,  43,  12,   8,  16,  20, 107,  77, 120, 145, 181,  85,  35,
        116, 146, 121,  31, 125,  76, 240,  89,   5, 244,  51, 102, 159,
         54, 104,  94,  71, 157,  24,  39, 123,   7, 191,  84,  36, 170,
        129, 246,  74, 180, 131, 150,  57,  27, 106, 133, 262, 248, 237,
        211, 177, 110, 101, 171,  46,  40,   1,   9, 233, 119, 163,  66,
         58,  90,   3, 113, 147, 206, 194,  38,  64,  67, 196, 132, 168,
        111, 161, 257, 115, 204,  47, 200, 236, 232, 175,  97, 141,  70,
        198, 228, 221,  83, 258, 255, 272, 138, 231, 169, 109, 217,  88,
        127, 271, 148,  82, 269, 186,  73, 202, 103

In [15]:
import numpy as np

# 기존 데이터와 오버샘플링된 데이터 합치기
X_combined = np.concatenate((X, X_oversampled))
y_combined = np.concatenate((y, y_oversampled))

In [16]:
X_combined.shape, y_combined.shape

((151011, 6), (151011,))

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X_combined, y_combined, test_size=0.2, random_state=42, stratify=y_combined)

In [19]:
import xgboost as xgb
# xgboost 모델 생성
model = xgb.XGBClassifier(objective='multi:softmax', num_class=273)

# 모델 학습
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_class=273,
              num_parallel_tree=None, objective='multi:softmax', ...)

In [20]:
# 예측 결과 출력
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.10644637949872529


In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# 테스트 데이터에 대한 예측 수행

# 정확도 계산
accuracy = accuracy_score(y_test, y_pred)

# 정밀도 계산
precision = precision_score(y_test, y_pred, average='micro')

# 재현율 계산
recall = recall_score(y_test, y_pred, average='micro')

# F1 스코어 계산
f1 = f1_score(y_test, y_pred, average='micro')

# 결과 출력
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Accuracy: 0.10644637949872529
Precision: 0.10644637949872529
Recall: 0.10644637949872529
F1 Score: 0.10644637949872529


In [48]:
y_train.unique()

array([ 12,  74,   4,  36,  61, 108,  79, 116, 224,   6, 145,  13, 181,
         2,  14,  80,   0, 216, 132,  71,  15,  30, 179,  66,  62,  11,
        53,  70,  96,  17, 244, 112,  31, 102, 156,  34, 134,  99,  21,
        43,  41,   1, 115, 190, 203,  18, 146,  39, 124, 164, 180, 103,
       202,  22,  60,  91, 117, 207, 105,  50,  76,   9,  10,  97,  37,
        92,  23,  49, 260,  19,  81,  73,   3,  56,  45, 111, 194,  68,
       119,  46, 129, 125, 257, 107,   8,  20,  58,  94, 139, 101,  87,
        85,  75, 157, 169,   5,  77,  59, 153,  84, 178,  86, 123,  72,
        16,  32, 100,  25, 137, 159, 110,  78,   7,  52,  65, 122,  93,
       133,  90,  24, 213,  51, 106, 148, 186,  35,  28,  48,  89,  69,
        29, 114,  33, 147, 152,  55,  63, 136, 166, 189, 177,  38,  44,
        26,  67,  88, 140, 196, 182, 142, 113, 138, 104, 120, 239,  82,
       121, 211, 191, 199, 227,  42, 241,  27, 269, 212, 192, 163, 197,
       154, 193, 135, 172,  57, 109, 158,  54,  40, 240,  64, 13

In [ ]:
# xgboost 모델 생성
model = xgb.XGBClassifier(objective='multi:softmax', num_class=273)

# 모델 학습
model.fit(X_train, y_train)

# 예측 결과 출력
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))