In [50]:
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv('../data/raw_postpro.csv', encoding='cp949')
df1 = df[["청구품목", 'key2', '리드타임', '견적화폐' , '발주처']]
df1["leadtime"] = df["리드타임"].astype(int)

C:\Users\peos0\AppData\Local\Temp\ipykernel_11352\323329017.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["leadtime"] = df["리드타임"].astype(int)


In [5]:
df1

청구품목      key2  리드타임 견적화폐   
0                         SEAL-O-RING-STOR    COOLER   194  KRW  \
1                       OIL COOLER & LINES    COOLER    59  KRW   
2                                   WASHER    COOLER    61  KRW   
3                           BOLT-HIGH TEMP    COOLER   212  KRW   
4                                     SEAL    COOLER   220  KRW   
...                                    ...       ...   ...  ...   
20512         HYD. CYLINDER_NET BOAT DAVIT  CYLINDER    95  JPY   
20513  HYD. CYLINDER_N.D CRANE_BOOM_LIFTER  CYLINDER    67  JPY   
20514                                PULLY      BELT    25  JPY   
20515                            CYLINDER   CYLINDER    25  JPY   
20516                SEAL KIT FOR CYLINDER  CYLINDER    25  JPY   

                                    발주처  leadtime  
0              HAEIN Coporation_Cheonan       194  
1              HAEIN Coporation_Cheonan        59  
2              HAEIN Coporation_Cheonan        61  
3              HAEIN Coporation_Cheonan       212  
4              HAEIN Coporation_Cheonan       220  
...                                 ...       ...  
20512          MARINE HYDROTEC CO.,LTD.        95  
20513          MARINE HYDROTEC CO.,LTD.        67  
20514  PORT RELIEF ENGINEERING CO.,LTD.        25  
20515  PORT RELIEF ENGINEERING CO.,LTD.        25  
20516  PORT RELIEF ENGINEERING CO.,LTD.        25  

[20517 rows x 6 columns]

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense

# 입력과 출력 데이터 분리
X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
y = df1['leadtime']

# LabelEncoder를 사용하여 범주형 변수를 정수로 인코딩
label_encoder = LabelEncoder()
for col in X.columns:
    X[col] = label_encoder.fit_transform(X[col])

# 학습 및 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # 회귀 모델 구축
# model = Sequential()
# model.add(Dense(64, activation='relu', input_dim=X_train.shape[1]))
# model.add(Dense(64, activation='relu'))
# model.add(Dense(1))

# 회귀 모델 구축
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))


C:\Users\peos0\AppData\Local\Temp\ipykernel_11352\2122652185.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = label_encoder.fit_transform(X[col])
C:\Users\peos0\AppData\Local\Temp\ipykernel_11352\2122652185.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = label_encoder.fit_transform(X[col])
C:\Users\peos0\AppData\Local\Temp\ipykernel_11352\2122652185.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_ind

In [51]:
# y # 정규화
from sklearn.preprocessing import StandardScaler

# 정규화할 y 값
y = df1['leadtime']

# StandardScaler 객체 생성
scaler = StandardScaler()

# y 값 정규화
y_normalized = scaler.fit_transform(y.values.reshape(-1, 1))

# 정규화된 y 값 출력
print(y_normalized.shape)

(20517, 1)


In [53]:
# print(y.shape)
y_normalized

array([[ 1.69446775],
       [-0.24214243],
       [-0.21345191],
       ...,
       [-0.72988129],
       [-0.72988129],
       [-0.72988129]])

In [54]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense

# 학습 및 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y_normalized, test_size=0.2, random_state=42)

# 회귀 모델 구축
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

In [55]:
# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
# 모델 학습
model.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
513/513 [==============================] - 1s 826us/step - loss: 84.6939
Epoch 2/100
513/513 [==============================] - 0s 848us/step - loss: 1.5388
Epoch 3/100
513/513 [==============================] - 0s 852us/step - loss: 3.9233
Epoch 4/100
513/513 [==============================] - 0s 877us/step - loss: 11.7978
Epoch 5/100
513/513 [==============================] - 0s 871us/step - loss: 8.1048
Epoch 6/100
513/513 [==============================] - 0s 871us/step - loss: 6.6781
Epoch 7/100
513/513 [==============================] - 0s 880us/step - loss: 7.6033
Epoch 8/100
513/513 [==============================] - 0s 878us/step - loss: 7.1942
Epoch 9/100
513/513 [==============================] - 0s 879us/step - loss: 3.5244
Epoch 10/100
513/513 [==============================] - 0s 875us/step - loss: 3.6904
Epoch 11/100
513/513 [==============================] - 0s 863us/step - loss: 5.1723
Epoch 12/100
513/513 [==============================] - 0s 871us/step - 

In [42]:
# 모델 평가
loss = model.evaluate(X_test, y_test)

129/129 [==============================] - 0s 699us/step - loss: 10545.0234


In [43]:
# 예측
predictions = model.predict(X_test)

129/129 [==============================] - 0s 684us/step


In [44]:
y_test

array([[145.],
       [ 78.],
       [ 56.],
       ...,
       [  5.],
       [  0.],
       [ 80.]])

In [45]:
predictions.shape

(4104, 1)

In [46]:
# 정규화된 y 예측 결과 확인
for i in range(100):
    print(f"실제 시간: {y_test[i][0]}, 예측 시간: {predictions[i][0]}")

실제 시간: 145.0, 예측 시간: 0.00213864678516984
실제 시간: 78.0, 예측 시간: 0.00213864678516984
실제 시간: 56.0, 예측 시간: 0.00213864678516984
실제 시간: 108.0, 예측 시간: 0.00213864678516984
실제 시간: 220.0, 예측 시간: 0.00213864678516984
실제 시간: 43.0, 예측 시간: 0.00213864678516984
실제 시간: 100.0, 예측 시간: 0.00213864678516984
실제 시간: 156.0, 예측 시간: 0.00213864678516984
실제 시간: 10.0, 예측 시간: 0.00213864678516984
실제 시간: 11.0, 예측 시간: 0.00213864678516984
실제 시간: 195.0, 예측 시간: 0.00213864678516984
실제 시간: 153.0, 예측 시간: 0.00213864678516984
실제 시간: 48.0, 예측 시간: 0.00213864678516984
실제 시간: 15.0, 예측 시간: 0.00213864678516984
실제 시간: 59.0, 예측 시간: 0.00213864678516984
실제 시간: 145.0, 예측 시간: 0.00213864678516984
실제 시간: 21.0, 예측 시간: 0.00213864678516984
실제 시간: 42.0, 예측 시간: 0.00213864678516984
실제 시간: 6.0, 예측 시간: 0.00213864678516984
실제 시간: 46.0, 예측 시간: 0.00213864678516984
실제 시간: 3.000000000000014, 예측 시간: 0.00213864678516984
실제 시간: 132.0, 예측 시간: 0.00213864678516984
실제 시간: 3.000000000000014, 예측 시간: 0.00213864678516984
실제 시간: 14.0, 예측 시간: 0.00213864678516984
실제 시간:

In [47]:
y_test = scaler.inverse_transform(y_test)
y_test

array([[10183.74756166],
       [ 5513.21547459],
       [ 3979.60792361],
       ...,
       [  424.42678271],
       [   75.87961203],
       [ 5652.63434286]])

In [48]:
predictions =  scaler.inverse_transform(predictions)
predictions

array([[76.028694],
       [76.028694],
       [76.028694],
       ...,
       [76.028694],
       [76.028694],
       [76.028694]], dtype=float32)

In [49]:
# y 예측 결과 확인
for i in range(100):
    print(f"실제 시간: {y_test[i][0]}, 예측 시간: {predictions[i][0]}")

실제 시간: 10183.747561656593, 예측 시간: 76.02869415283203
실제 시간: 5513.215474587314, 예측 시간: 76.02869415283203
실제 시간: 3979.607923609342, 예측 시간: 76.02869415283203
실제 시간: 7604.498498648185, 예측 시간: 76.02869415283203
실제 시간: 15411.95512180877, 예측 시간: 76.02869415283203
실제 시간: 3073.385279849631, 예측 시간: 76.02869415283203
실제 시간: 7046.823025565286, 예측 시간: 76.02869415283203
실제 시간: 10950.55133714558, 예측 시간: 76.02869415283203
실제 시간: 772.9739533826728, 예측 시간: 76.02869415283203
실제 시간: 842.6833875180351, 예측 시간: 76.02869415283203
실제 시간: 13669.219268424713, 예측 시간: 76.02869415283203
실제 시간: 10741.423034739493, 예측 시간: 76.02869415283203
실제 시간: 3421.932450526443, 예측 시간: 76.02869415283203
실제 시간: 1121.5211240594845, 예측 시간: 76.02869415283203
실제 시간: 4188.736226015429, 예측 시간: 76.02869415283203
실제 시간: 10183.747561656593, 예측 시간: 76.02869415283203
실제 시간: 1539.7777288716588, 예측 시간: 76.02869415283203
실제 시간: 3003.6758457142687, 예측 시간: 76.02869415283203
실제 시간: 494.13621684122336, 예측 시간: 76.02869415283203
실제 시간: 3282.51358225571

In [34]:
# 회귀 모델 구축
model2 = Sequential()
model2.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model2.add(Dense(64, activation='relu'))
model2.add(Dense(32, activation='relu'))
model2.add(Dense(1))

In [36]:
# 모델 컴파일
model2.compile(optimizer='adam', loss='mean_squared_error')

In [37]:
# 모델 학습
model2.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
513/513 [==============================] - 1s 799us/step - loss: 5858.5386
Epoch 2/10
513/513 [==============================] - 0s 784us/step - loss: 5266.6533
Epoch 3/10
513/513 [==============================] - 0s 801us/step - loss: 5078.9551
Epoch 4/10
513/513 [==============================] - 0s 786us/step - loss: 4954.1279
Epoch 5/10
513/513 [==============================] - 0s 787us/step - loss: 4926.1978
Epoch 6/10
513/513 [==============================] - 0s 784us/step - loss: 4866.7661
Epoch 7/10
513/513 [==============================] - 0s 784us/step - loss: 4877.1812
Epoch 8/10
513/513 [==============================] - 0s 817us/step - loss: 4767.5371
Epoch 9/10
513/513 [==============================] - 0s 814us/step - loss: 4769.4419
Epoch 10/10
513/513 [==============================] - 0s 942us/step - loss: 4767.0117


In [38]:

# 모델 평가
loss = model2.evaluate(X_test, y_test)

129/129 [==============================] - 0s 568us/step - loss: 4720.4844


In [39]:
# 예측
predictions = model.predict(X_test)

129/129 [==============================] - 0s 624us/step


In [41]:
for i in range(len(predictions)):
    # print(f"실제 시간: {y_test.iloc[i]}, 예측 시간: {predictions[i][0]}")

SyntaxError: incomplete input (1878388943.py, line 2)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
X_encoded = X.copy()
le = LabelEncoder()
for col in X.columns:
    X_encoded[col] = le.fit_transform(X[col])
y = df1["leadtime"]
# X = np.array(X)
# y = np.array(y)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, random_state=40, shuffle=True, test_size=0.3)

In [16]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten
from sklearn.preprocessing import LabelEncoder


model = Sequential()
model.add(Dense(64, activation='relu', input_dim=4))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

In [17]:
X_encoded

청구품목  key2  견적화폐  발주처
0      4848    18     2   22
1      3692    18     2   22
2      5915    18     2   22
3       696    18     2   22
4      4681    18     2   22
...     ...   ...   ...  ...
20512  2811    20     1   35
20513  2810    20     1   35
20514  4151     5     1   41
20515  1592    20     1   41
20516  4718    20     1   41

[20517 rows x 4 columns]

In [18]:
# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')


In [21]:
# 모델 학습
model.fit(X_train, y_train, epochs=30, batch_size=20)

Epoch 1/30
719/719 [==============================] - 1s 718us/step - loss: 4570.3857
Epoch 2/30
719/719 [==============================] - 0s 685us/step - loss: 4455.8169
Epoch 3/30
719/719 [==============================] - 0s 684us/step - loss: 4454.7124
Epoch 4/30
719/719 [==============================] - 0s 686us/step - loss: 4419.8271
Epoch 5/30
719/719 [==============================] - 1s 708us/step - loss: 4414.2935
Epoch 6/30
719/719 [==============================] - 1s 786us/step - loss: 4395.2896
Epoch 7/30
719/719 [==============================] - 1s 799us/step - loss: 4435.3975
Epoch 8/30
719/719 [==============================] - 1s 787us/step - loss: 4419.7266
Epoch 9/30
719/719 [==============================] - 1s 812us/step - loss: 4406.4590
Epoch 10/30
719/719 [==============================] - 1s 853us/step - loss: 4388.4800
Epoch 11/30
719/719 [==============================] - 1s 875us/step - loss: 4410.8535
Epoch 12/30
719/719 [==============================]

In [22]:
# 모델 평가
loss = model.evaluate(X_test, y_test)

193/193 [==============================] - 0s 714us/step - loss: 4114.6880


In [23]:
# 예측
predictions = model.predict(X_test)

193/193 [==============================] - 0s 587us/step


In [24]:
predictions

array([[ 36.74128 ],
       [ 92.509026],
       [ 91.80747 ],
       ...,
       [101.08235 ],
       [ 44.686443],
       [ 84.99454 ]], dtype=float32)

In [26]:
# 예측 결과 확인
for i in range(len(predictions)):
    print(f"실제값: {y_test[i]}, 예측값: {predictions[i][0]}")

KeyError: 0