In [67]:
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv('../data/raw_postpro.csv', encoding='cp949')
df1 = df[["청구품목", 'key2', '리드타임', '견적화폐' , '발주처']]
df1["leadtime"] = df["리드타임"].astype(int)

C:\Users\SW\AppData\Local\Temp\ipykernel_988\323329017.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["leadtime"] = df["리드타임"].astype(int)


In [68]:
df.columns

Index(['청구서번호', 'No.', 'Subject', 'Machinery', 'Assembly', '청구품목', 'Part No.1',
       'Part No.2', 'key1', 'key2', '리드타임_음수제거', '청구량', '견적', '견적수량', '견적화폐',
       '견적단가', '발주번호', '발주처', '발주', '발주수량', '발주금액', 'D/T', '미입고 기간', '리드타임',
       '창고입고', '창고입고수량', 'Control No.', '입고창고', '창고출고', '창고출고수량', '출고선박',
       '출고운반선', '선박입고', '선박입고수량', '완료 여부'],
      dtype='object')

In [69]:
# df["리드타임"] = df["리드타임"].astype(float)
# df["key2"] = df["key2"].astype(int)
df1["leadtime"].iloc[:50,]

0     194
1      59
2      61
3     212
4     220
5      80
6     100
7      13
8     117
9      96
10      2
11    156
12     72
13     25
14     49
15     49
16     49
17     49
18     56
19     48
20     56
21     56
22     28
23      6
24     56
25     48
26     56
27     48
28      6
29      6
30     32
31      6
32      6
33      6
34      6
35      6
36      6
37      6
38      6
39      6
40      6
41      6
42      6
43      6
44      6
45      6
46      6
47      6
48     62
49     62
Name: leadtime, dtype: int32

In [70]:
df1

청구품목      key2  리드타임 견적화폐   
0                         SEAL-O-RING-STOR    COOLER   194  KRW  \
1                       OIL COOLER & LINES    COOLER    59  KRW   
2                                   WASHER    COOLER    61  KRW   
3                           BOLT-HIGH TEMP    COOLER   212  KRW   
4                                     SEAL    COOLER   220  KRW   
...                                    ...       ...   ...  ...   
20512         HYD. CYLINDER_NET BOAT DAVIT  CYLINDER    95  JPY   
20513  HYD. CYLINDER_N.D CRANE_BOOM_LIFTER  CYLINDER    67  JPY   
20514                                PULLY      BELT    25  JPY   
20515                            CYLINDER   CYLINDER    25  JPY   
20516                SEAL KIT FOR CYLINDER  CYLINDER    25  JPY   

                                    발주처  leadtime  
0              HAEIN Coporation_Cheonan       194  
1              HAEIN Coporation_Cheonan        59  
2              HAEIN Coporation_Cheonan        61  
3              HAEIN Coporation_Cheonan       212  
4              HAEIN Coporation_Cheonan       220  
...                                 ...       ...  
20512          MARINE HYDROTEC CO.,LTD.        95  
20513          MARINE HYDROTEC CO.,LTD.        67  
20514  PORT RELIEF ENGINEERING CO.,LTD.        25  
20515  PORT RELIEF ENGINEERING CO.,LTD.        25  
20516  PORT RELIEF ENGINEERING CO.,LTD.        25  

[20517 rows x 6 columns]

In [27]:
# 컬럼 값을 배열로 변환
leadtime_val = df1['leadtime'].values

# 로그 변환 전에 1을 더함
leadtime_val = np.log(leadtime_val + 1)

# 컬럼 추가
df1['leadtime+1'] = leadtime_val
# df1

C:\Users\SW\AppData\Local\Temp\ipykernel_988\3532539691.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['leadtime+1'] = leadtime_val


In [78]:
lead = df1['leadtime']
mean = np.mean(lead)

# 분산 계산
variance = np.var(lead)

# 결과 출력
print("평균:", mean)
print("분산:", variance)

평균: 75.87961202904908
분산: 4859.405207472425


In [74]:
df1['leadtime']

0        194
1         59
2         61
3        212
4        220
        ... 
20512     95
20513     67
20514     25
20515     25
20516     25
Name: leadtime, Length: 20517, dtype: int32

In [75]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

# 입력과 출력 데이터 분리
X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
y = df1['leadtime']
# y = df1['leadtime+1']
 
# LabelEncoder를 사용하여 범주형 변수를 정수로 인코딩
label_encoder = LabelEncoder()
for col in X.columns:
    X[col] = label_encoder.fit_transform(X[col])

    
# 정규화 대신에
# 로그 변환 
y = np.log(y+1)
# df['leadtime'] = np.log(df['leadtime'])
    
# y # 정규화
# from sklearn.preprocessing import StandardScaler

# 정규화할 y 값
# y = df1['leadtime']

# StandardScaler 객체 생성
# scaler = StandardScaler()

# y_normalized = scaler.fit_transform(y.values.reshape(-1, 1))    

# RobustScaler 객체 생성
# from sklearn.preprocessing import RobustScaler
# scaler = RobustScaler()
# 'leadtime' 컬럼에 로버스트 스케일링 적용
# y = np.array(y)
# y = y.reshape((-1, 1))
# y = scaler.fit_transform(y)


# X_train, X_test, y_train, y_test = train_test_split(X, y_normalized, test_size=0.2, random_state=42) # y 정규화 한 y_normalized
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

# 회귀 모델 구축
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))


C:\Users\SW\AppData\Local\Temp\ipykernel_988\3542545691.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = label_encoder.fit_transform(X[col])
C:\Users\SW\AppData\Local\Temp\ipykernel_988\3542545691.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = label_encoder.fit_transform(X[col])
C:\Users\SW\AppData\Local\Temp\ipykernel_988\3542545691.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value i

In [76]:
y_test, y_train

(1493     4.983607
 8503     4.369448
 7408     4.043051
 3509     4.691348
 5927     5.398163
            ...   
 17651    3.912023
 9659     4.290459
 13418    1.791759
 8410     0.000000
 16062    4.394449
 Name: leadtime, Length: 4104, dtype: float64,
 7854     2.564949
 20118    4.317488
 8523     1.609438
 18477    3.610918
 483      4.127134
            ...   
 11284    2.564949
 11964    5.056246
 5390     0.693147
 860      0.000000
 15795    2.197225
 Name: leadtime, Length: 16413, dtype: float64)

In [67]:
# # y # 정규화
# from sklearn.preprocessing import StandardScaler

# # 정규화할 y 값
# y = df1['leadtime']

# # StandardScaler 객체 생성
# scaler = StandardScaler()

# # y 값 정규화
# y_normalized = scaler.fit_transform(y.values.reshape(-1, 1))

# # 정규화된 y 값 출력
# print(y_normalized.shape)
y_train, y_test

(array([[-0.53409091],
        [ 0.17045455],
        [-0.625     ],
        ...,
        [-0.65909091],
        [-0.67045455],
        [-0.57954545]]),
 array([[ 0.97727273],
        [ 0.21590909],
        [-0.03409091],
        ...,
        [-0.61363636],
        [-0.67045455],
        [ 0.23863636]]))

In [190]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense

# 학습 및 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y_normalized, test_size=0.2, random_state=42)

# 회귀 모델 구축
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

In [77]:
# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')

In [78]:
# 모델 학습
model.fit(X_train, y_train, epochs=15, batch_size=32)

Epoch 1/15
513/513 [==============================] - 1s 819us/step - loss: 46.1961
Epoch 2/15
513/513 [==============================] - 0s 801us/step - loss: 8.5670
Epoch 3/15
513/513 [==============================] - 0s 835us/step - loss: 14.4204
Epoch 4/15
513/513 [==============================] - 0s 821us/step - loss: 9.6380
Epoch 5/15
513/513 [==============================] - 0s 817us/step - loss: 5.2195
Epoch 6/15
513/513 [==============================] - 0s 845us/step - loss: 9.0231
Epoch 7/15
513/513 [==============================] - 0s 817us/step - loss: 3.3240
Epoch 8/15
513/513 [==============================] - 0s 849us/step - loss: 3.9524
Epoch 9/15
513/513 [==============================] - 0s 839us/step - loss: 3.7343
Epoch 10/15
513/513 [==============================] - 0s 846us/step - loss: 2.6680
Epoch 11/15
513/513 [==============================] - 0s 835us/step - loss: 3.0898
Epoch 12/15
513/513 [==============================] - 0s 820us/step - loss: 3.4187

In [79]:
# 모델 평가
loss = model.evaluate(X_test, y_test)

129/129 [==============================] - 0s 678us/step - loss: 1.3782


In [80]:
# 예측
predictions = model.predict(X_test)

129/129 [==============================] - 0s 600us/step


In [81]:
y_test, predictions

(1493     4.983607
 8503     4.369448
 7408     4.043051
 3509     4.691348
 5927     5.398163
            ...   
 17651    3.912023
 9659     4.290459
 13418    1.791759
 8410     0.000000
 16062    4.394449
 Name: leadtime, Length: 4104, dtype: float64,
 array([[3.9088748],
        [3.689872 ],
        [3.803645 ],
        ...,
        [3.3755481],
        [3.4619353],
        [3.3363895]], dtype=float32))

In [82]:
y_test = np.exp(y_test)-1
predictions = np.exp(predictions)-1

In [93]:
type(y_test), type(predictions)#.shape, predictions.shape
# for i in range(100):
    # print(f"실제 시간: {y_test[i]}")
# y_test[:]

(pandas.core.series.Series, numpy.ndarray)

In [98]:
# y_test = y_test.values
y_test.shape,predictions.shape

((4104,), (4104, 1))

In [55]:
# 원래 스케일로 되돌리기
y_test = scaler.inverse_transform(y_test)
predictions = scaler.inverse_transform(predictions)

In [100]:
# 정규화된 y 예측 결과 확인
for i in range(100):
    print(f"실제 시간: {y_test[i]}, 예측 시간: {predictions[i][0]}")

실제 시간: 145.0, 예측 시간: 48.842838287353516
실제 시간: 78.0, 예측 시간: 39.03972244262695
실제 시간: 56.00000000000001, 예측 시간: 43.86441421508789
실제 시간: 107.99999999999997, 예측 시간: 41.13968276977539
실제 시간: 219.99999999999991, 예측 시간: 24.366891860961914
실제 시간: 42.99999999999999, 예측 시간: 46.24018478393555
실제 시간: 100.00000000000003, 예측 시간: 27.40373420715332
실제 시간: 155.99999999999994, 예측 시간: 35.377201080322266
실제 시간: 10.000000000000002, 예측 시간: 31.375652313232422
실제 시간: 11.0, 예측 시간: 19.52713966369629
실제 시간: 194.99999999999991, 예측 시간: 56.42695236206055
실제 시간: 153.00000000000006, 예측 시간: 30.709692001342773
실제 시간: 47.99999999999999, 예측 시간: 50.7730712890625
실제 시간: 14.999999999999998, 예측 시간: 17.339994430541992
실제 시간: 58.999999999999986, 예측 시간: 27.469881057739258
실제 시간: 145.0, 예측 시간: 41.238277435302734
실제 시간: 21.000000000000004, 예측 시간: 19.050567626953125
실제 시간: 42.0, 예측 시간: 15.534904479980469
실제 시간: 5.999999999999999, 예측 시간: 33.488197326660156
실제 시간: 45.99999999999999, 예측 시간: 37.1999397277832
실제 시간: 3.0, 예측 시간: 29.83

In [47]:
y_test = scaler.inverse_transform(y_test)
y_test

array([[10183.74756166],
       [ 5513.21547459],
       [ 3979.60792361],
       ...,
       [  424.42678271],
       [   75.87961203],
       [ 5652.63434286]])

In [48]:
predictions =  scaler.inverse_transform(predictions)
predictions

array([[76.028694],
       [76.028694],
       [76.028694],
       ...,
       [76.028694],
       [76.028694],
       [76.028694]], dtype=float32)

In [49]:
# y 예측 결과 확인
for i in range(100):
    print(f"실제 시간: {y_test[i][0]}, 예측 시간: {predictions[i][0]}")

실제 시간: 10183.747561656593, 예측 시간: 76.02869415283203
실제 시간: 5513.215474587314, 예측 시간: 76.02869415283203
실제 시간: 3979.607923609342, 예측 시간: 76.02869415283203
실제 시간: 7604.498498648185, 예측 시간: 76.02869415283203
실제 시간: 15411.95512180877, 예측 시간: 76.02869415283203
실제 시간: 3073.385279849631, 예측 시간: 76.02869415283203
실제 시간: 7046.823025565286, 예측 시간: 76.02869415283203
실제 시간: 10950.55133714558, 예측 시간: 76.02869415283203
실제 시간: 772.9739533826728, 예측 시간: 76.02869415283203
실제 시간: 842.6833875180351, 예측 시간: 76.02869415283203
실제 시간: 13669.219268424713, 예측 시간: 76.02869415283203
실제 시간: 10741.423034739493, 예측 시간: 76.02869415283203
실제 시간: 3421.932450526443, 예측 시간: 76.02869415283203
실제 시간: 1121.5211240594845, 예측 시간: 76.02869415283203
실제 시간: 4188.736226015429, 예측 시간: 76.02869415283203
실제 시간: 10183.747561656593, 예측 시간: 76.02869415283203
실제 시간: 1539.7777288716588, 예측 시간: 76.02869415283203
실제 시간: 3003.6758457142687, 예측 시간: 76.02869415283203
실제 시간: 494.13621684122336, 예측 시간: 76.02869415283203
실제 시간: 3282.51358225571

In [34]:
# 회귀 모델 구축
model2 = Sequential()
model2.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model2.add(Dense(64, activation='relu'))
model2.add(Dense(32, activation='relu'))
model2.add(Dense(1))

In [36]:
# 모델 컴파일
model2.compile(optimizer='adam', loss='mean_squared_error')

In [37]:
# 모델 학습
model2.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
513/513 [==============================] - 1s 799us/step - loss: 5858.5386
Epoch 2/10
513/513 [==============================] - 0s 784us/step - loss: 5266.6533
Epoch 3/10
513/513 [==============================] - 0s 801us/step - loss: 5078.9551
Epoch 4/10
513/513 [==============================] - 0s 786us/step - loss: 4954.1279
Epoch 5/10
513/513 [==============================] - 0s 787us/step - loss: 4926.1978
Epoch 6/10
513/513 [==============================] - 0s 784us/step - loss: 4866.7661
Epoch 7/10
513/513 [==============================] - 0s 784us/step - loss: 4877.1812
Epoch 8/10
513/513 [==============================] - 0s 817us/step - loss: 4767.5371
Epoch 9/10
513/513 [==============================] - 0s 814us/step - loss: 4769.4419
Epoch 10/10
513/513 [==============================] - 0s 942us/step - loss: 4767.0117


In [38]:

# 모델 평가
loss = model2.evaluate(X_test, y_test)

129/129 [==============================] - 0s 568us/step - loss: 4720.4844


In [39]:
# 예측
predictions = model.predict(X_test)

129/129 [==============================] - 0s 624us/step


In [41]:
for i in range(len(predictions)):
    # print(f"실제 시간: {y_test.iloc[i]}, 예측 시간: {predictions[i][0]}")

SyntaxError: incomplete input (1878388943.py, line 2)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
X_encoded = X.copy()
le = LabelEncoder()
for col in X.columns:
    X_encoded[col] = le.fit_transform(X[col])
y = df1["leadtime"]
# X = np.array(X)
# y = np.array(y)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, random_state=40, shuffle=True, test_size=0.3)

In [16]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten
from sklearn.preprocessing import LabelEncoder


model = Sequential()
model.add(Dense(64, activation='relu', input_dim=4))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

In [17]:
X_encoded

청구품목  key2  견적화폐  발주처
0      4848    18     2   22
1      3692    18     2   22
2      5915    18     2   22
3       696    18     2   22
4      4681    18     2   22
...     ...   ...   ...  ...
20512  2811    20     1   35
20513  2810    20     1   35
20514  4151     5     1   41
20515  1592    20     1   41
20516  4718    20     1   41

[20517 rows x 4 columns]

In [18]:
# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')


In [21]:
# 모델 학습
model.fit(X_train, y_train, epochs=30, batch_size=20)

Epoch 1/30
719/719 [==============================] - 1s 718us/step - loss: 4570.3857
Epoch 2/30
719/719 [==============================] - 0s 685us/step - loss: 4455.8169
Epoch 3/30
719/719 [==============================] - 0s 684us/step - loss: 4454.7124
Epoch 4/30
719/719 [==============================] - 0s 686us/step - loss: 4419.8271
Epoch 5/30
719/719 [==============================] - 1s 708us/step - loss: 4414.2935
Epoch 6/30
719/719 [==============================] - 1s 786us/step - loss: 4395.2896
Epoch 7/30
719/719 [==============================] - 1s 799us/step - loss: 4435.3975
Epoch 8/30
719/719 [==============================] - 1s 787us/step - loss: 4419.7266
Epoch 9/30
719/719 [==============================] - 1s 812us/step - loss: 4406.4590
Epoch 10/30
719/719 [==============================] - 1s 853us/step - loss: 4388.4800
Epoch 11/30
719/719 [==============================] - 1s 875us/step - loss: 4410.8535
Epoch 12/30
719/719 [==============================]

In [22]:
# 모델 평가
loss = model.evaluate(X_test, y_test)

193/193 [==============================] - 0s 714us/step - loss: 4114.6880


In [23]:
# 예측
predictions = model.predict(X_test)

193/193 [==============================] - 0s 587us/step


In [24]:
predictions

array([[ 36.74128 ],
       [ 92.509026],
       [ 91.80747 ],
       ...,
       [101.08235 ],
       [ 44.686443],
       [ 84.99454 ]], dtype=float32)

In [26]:
# 예측 결과 확인
for i in range(len(predictions)):
    print(f"실제값: {y_test[i]}, 예측값: {predictions[i][0]}")

KeyError: 0