In [160]:
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv('../data/raw_postpro.csv')
df1 = df[["청구품목", 'key2', 'leadtime', '견적화폐' , '발주처']]
df1["leadtime"] = df["leadtime"].astype(int)

C:\Users\peos0\AppData\Local\Temp\ipykernel_17276\1378052945.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["leadtime"] = df["leadtime"].astype(int)


In [161]:
df.columns

Index(['청구서번호', 'No.', 'Subject', 'Machinery', 'Assembly', '청구품목', 'Part No.1',
       'Part No.2', 'key1', 'key2', 'leadtime', '청구량', '견적', '견적수량', '견적화폐',
       '견적단가', '발주번호', '발주처', '발주', '발주수량', '발주금액'],
      dtype='object')

In [162]:
# df["리드타임"] = df["리드타임"].astype(float)
# df["key2"] = df["key2"].astype(int)
df1["leadtime"].iloc[:50,]

0     194
1      59
2      61
3     212
4     220
5      80
6     100
7      13
8     117
9      96
10      2
11    156
12     72
13     25
14     49
15     49
16     49
17     49
18     56
19     48
20     56
21     56
22     28
23      6
24     56
25     48
26     56
27     48
28      6
29      6
30     32
31      6
32      6
33      6
34      6
35      6
36      6
37      6
38      6
39      6
40      6
41      6
42      6
43      6
44      6
45      6
46      6
47      6
48     62
49     62
Name: leadtime, dtype: int32

In [54]:
df

청구서번호  No.   
0      ELS-BS-ESP-2004002   12  \
1      OCA-BS-ESP-2010004    5   
2      MIR-BS-ESP-2011002  119   
3      BLO-BS-ESP-2003002   16   
4      DEO-BS-ESP-2105008   97   
...                   ...  ...   
20512  BLO-BS-ESP-2006006    1   
20513  BLO-BS-ESP-2004008    1   
20514  ELS-BS-ESP-1908002    2   
20515  BLO-BS-ESP-1906014    2   
20516  BLO-BS-ESP-1906014    3   

                                                 Subject   
0                           NO.1 A/E C18 MAJOR O/H PARTS  \
1                   운전시간 대비 #2 AUX ENG TOP END O/H PARTS   
2          운전시간 대비 #2 AUX ENG(CAT 3512C) MAJOR O/H PARTS   
3                           #1 AUX ENG TOP END O/H PARTS   
4                                        DEO-E-210512-01   
...                                                  ...   
20512  BLO-F-ENGINE-200515-03 BOAT DAVIT CYL 외, AIRCO...   
20513  BLO-F-ENGINE-200403-01 (NAVI DECK CRANE DERRIN...   
20514                                ELS-F-ENG-190628-02   
20515            BLO-F-ENGINE-190617-01 (NET BOAT PARTS)   
20516            BLO-F-ENGINE-190617-01 (NET BOAT PARTS)   

                   Machinery                              Assembly   
0      NO.1 GENERATOR ENGINE               323-6480 LINES GP-FUEL   \
1      NO.2 GENERATOR ENGINE                            GASKET KIT   
2      NO.2 GENERATOR ENGINE             285-8374 MANIFOLD GP-EXH    
3      NO.1 GENERATOR ENGINE                     159-8828 TURBO GP   
4      NO.1 GENERATOR ENGINE             2N4727 INSTRUMNT PANEL GP   
...                      ...                                   ...   
20512            HYD. SYSTEM  5-753-2E_BOAT DAVIT & N.D CRANE LINE   
20513            HYD. SYSTEM  5-753-2E_BOAT DAVIT & N.D CRANE LINE   
20514            6M NET BOAT                       ELECTRIC CLUTCH   
20515            7M NET BOAT        HAND HYDRAULIC STEERING SYSTEM   
20516            7M NET BOAT        HAND HYDRAULIC STEERING SYSTEM   

                                      청구품목                     Part No.1   
0                         SEAL-O-RING-STOR                     7.00E-275  \
1                       OIL COOLER & LINES                     7.00E-275   
2                                   WASHER                     7.00E-275   
3                           BOLT-HIGH TEMP                     7.00E-275   
4                                     SEAL                     7.00E-275   
...                                    ...                           ...   
20512         HYD. CYLINDER_NET BOAT DAVIT            φ150 × φ85 × 695st   
20513  HYD. CYLINDER_N.D CRANE_BOOM_LIFTER          φ160 × φ112 × 1130st   
20514                                PULLY                     Φ305X5V-3   
20515                            CYLINDER            Φ50 x S195 CYLINDER   
20516                SEAL KIT FOR CYLINDER  Φ50 x S195 CYLINDER SEAL KIT   

                       Part No.2                                         key1   
0                              0                                    7.00E-275  \
1                              0                                    7.00E-275   
2                              0                                    7.00E-275   
3                              0                                    7.00E-275   
4                              0                                    7.00E-275   
...                          ...                                          ...   
20512  FF-SE-1CB150BB695ABD-YP2J  φ150 × φ85 × 695stFF-SE-1CB150BB695ABD-YP2J   
20513       S-2CA160A20.6N1130-1     φ160 × φ112 × 1130stS-2CA160A20.6N1130-1   
20514                          0                                    Φ305X5V-3   
20515                          0                          Φ50 x S195 CYLINDER   
20516                          0                 Φ50 x S195 CYLINDER SEAL KIT   

           key2  ...  Control No.  입고창고        창고출고  창고출고수량 출고선박   
0        COOLER  ...        혜인 발주    BS  2020-09-19       1  BLO  \
1        COOLER  ...       

In [164]:
# # 컬럼 값을 배열로 변환
# leadtime_val = df1['leadtime'].values

# # 로그 변환 전에 1을 더함
# leadtime_val = np.log(leadtime_val + 1)

# # 컬럼 추가
# df1['leadtime+1'] = leadtime_val
# # df1

In [94]:
lead = df1['leadtime']
mean = np.mean(lead)

# 분산 계산
variance = np.var(lead)

# 결과 출력
print("평균:", mean)
print("분산:", variance)

평균: 75.87961202904908
분산: 4859.405207472425


## X 값 CountVectorizer로 벡터화

In [166]:
from gensim.models import FastText
from sklearn.feature_extraction.text import CountVectorizer
columns = ["청구품목", 'key2', '견적화폐' , '발주처']
embedings = []
for col in columns:
    documents = df1[col].tolist()

    # FastText 모델 학습
    model = FastText(sentences=[doc.split() for doc in documents], vector_size=100, window=5, min_count=1, sg=1)

    # 벡터화된 데이터 초기화
    vectors = []

    # 각 문서에 대해 벡터 생성
    for doc in documents:
        vector = np.zeros(model.vector_size)
        count = 0
        for word in doc.split():
            if word in model.wv:
                vector += model.wv[word]
                count += 1
        if count > 0:
            vector /= count
        vectors.append(vector)

    # 벡터화된 데이터를 배열로 변환
    vectors = np.array(vectors)
    embedings.append(vectors)
embedings

[array([[ 0.32960573,  0.24851812,  0.06808377, ...,  0.1573064 ,
         -0.00786069, -0.00632482],
        [ 0.39576685,  0.27333339,  0.25200067, ...,  0.02028716,
         -0.14610704,  0.06637021],
        [ 0.58400959,  0.41025952,  0.04676579, ...,  0.31154883,
         -0.03559348, -0.04781994],
        ...,
        [ 0.09543514,  0.075695  ,  0.00617669, ...,  0.02922439,
         -0.01538001,  0.01251636],
        [ 0.38479483,  0.36420766,  0.0685482 , ...,  0.06444658,
          0.01584299,  0.12406273],
        [ 0.38979992,  0.31148088,  0.14055318, ...,  0.06891228,
         -0.03269082,  0.10842492]]),
 array([[ 0.00109761, -0.00138392, -0.00077547, ..., -0.00037611,
         -0.00151895,  0.00137649],
        [ 0.00109761, -0.00138392, -0.00077547, ..., -0.00037611,
         -0.00151895,  0.00137649],
        [ 0.00109761, -0.00138392, -0.00077547, ..., -0.00037611,
         -0.00151895,  0.00137649],
        ...,
        [ 0.00114423,  0.00317362,  0.00134651, ...,  

In [169]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# 각 컬럼을 임베딩하여 벡터로 표현
embeddings_col1 = embedings[0]
embeddings_col2 = embedings[1]
embeddings_col3 = embedings[2]
embeddings_col4 = embedings[3]

# 예측 대상 데이터
target_data = df1['leadtime'].values

# 피처 벡터 생성
X = np.concatenate([embeddings_col1, embeddings_col2, embeddings_col3, embeddings_col4], axis=1)

# 학습 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, target_data, test_size=0.2, random_state=42)

# 선형 회귀 모델 학습
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [150]:
X.shape, y.shape
# X
# y

((20517, 400), (20517,))

## 결과확인
### 오차가 너무 많이 나고 예측 값에 음수가 들어감

In [171]:
# 테스트 데이터에 대한 예측
predictions = model.predict(X_test)

# 예측값과 실제값 비교
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': predictions})
# print(comparison)
comparison[:30]

Actual   Predicted
0      145  100.373932
1       78  103.280182
2       56  103.592682
3      108   86.498932
4      220  107.498932
5       43   88.936432
6      100   54.092682
7      156  107.717682
8       10   75.655182
9       11   10.748932
10     195   93.217682
11     153   67.811432
12      48  139.217682
13      15   38.952545
14      59   90.280182
15     145   95.905182
16      21   -5.981537
17      42   27.092682
18       6   61.967682
19      46   68.530182
20       3   80.186432
21     132   89.155182
22       3   62.498932
23      14    4.390533
24     370  233.354401
25       0   72.155182
26     140   99.655182
27     105   92.405182
28      91   76.686432
29      82  108.467682

In [173]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, fbeta_score, r2_score

# R 제곱 계산
r2 = r2_score(y_test, predictions)
print("R-squared:", r2)

## R 제곱 값이 음수인 경우는 모델이 주어진 데이터를 설명하지 못하는 경우를 의미
## => 모델이 이상함

# 평균 제곱 오차 계산
mse = mean_squared_error(y_test, predictions)
print("Mean Squared Error:", mse)

# 평균 절대 오차 계산
mae = mean_absolute_error(y_test, predictions)
print("Mean Absolute Error:", mae)

R-squared: -6.06742752758222e+18
Mean Squared Error: 2.914279238763171e+22
Mean Absolute Error: 5213809975.182478


## lstm
### 속도가 너무 느리고 정확도가 너무 낮음

In [174]:
from gensim.models import FastText
from sklearn.feature_extraction.text import CountVectorizer
columns = ["청구품목", 'key2', '견적화폐' , '발주처']
embedings = []
for col in columns:
    documents = df1[col].tolist()

    # FastText 모델 학습
    model = FastText(sentences=[doc.split() for doc in documents], vector_size=100, window=5, min_count=1, sg=1)

    # 벡터화된 데이터 초기화
    vectors = []

    # 각 문서에 대해 벡터 생성
    for doc in documents:
        vector = np.zeros(model.vector_size)
        count = 0
        for word in doc.split():
            if word in model.wv:
                vector += model.wv[word]
                count += 1
        if count > 0:
            vector /= count
        vectors.append(vector)

    # 벡터화된 데이터를 배열로 변환
    vectors = np.array(vectors)
    embedings.append(vectors)


In [154]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

# 각 컬럼을 임베딩하여 벡터로 표현
embeddings_col1 = embedings[0]
embeddings_col2 = embedings[1]
embeddings_col3 = embedings[2]
embeddings_col4 = embedings[3]

# 예측 대상 데이터
target_data = df1['leadtime'].values

# 피처 벡터 생성
X = np.concatenate([embeddings_col1, embeddings_col2, embeddings_col3, embeddings_col4], axis=1)

# 학습 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, target_data, test_size=0.2, random_state=42)

# 입력 데이터를 3차원으로 변환
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

# 모델 구성
model = Sequential()
model.add(LSTM(128, input_shape=(400,1)))
model.add(Dense(1))

# 모델 컴파일
model.compile(loss='mean_squared_error', optimizer='adam')

# 모델 학습
model.fit(X_train, y_train, epochs=10, batch_size=32)

# 모델 예측
predictions = model.predict(X_test)

# 모델 평가
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

Epoch 1/10
513/513 [==============================] - 114s 220ms/step - loss: 6419.7935
Epoch 2/10
513/513 [==============================] - 107s 209ms/step - loss: 4930.2437
Epoch 3/10
513/513 [==============================] - 107s 209ms/step - loss: 4875.2896
Epoch 4/10
513/513 [==============================] - 105s 205ms/step - loss: 4874.1626
Epoch 5/10
513/513 [==============================] - 110s 213ms/step - loss: 4874.2798
Epoch 6/10
513/513 [==============================] - 105s 204ms/step - loss: 4874.4438
Epoch 7/10
513/513 [==============================] - 105s 204ms/step - loss: 4873.9653
Epoch 8/10
513/513 [==============================] - 100s 195ms/step - loss: 4872.1475
Epoch 9/10
513/513 [==============================] - 104s 203ms/step - loss: 4846.7495
Epoch 10/10
129/129 [==============================] - 11s 83ms/step


In [156]:
mse, r2

(4685.995824328256, 0.024392045879199853)

In [179]:
X_train.shape, y_train.shape

((16413, 400), (16413,))

## cnn + lstm

In [199]:
X_train.shape

(12309, 1, 400)

In [217]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, Reshape, Flatten

# 피처 벡터 생성
X = np.concatenate([embeddings_col1, embeddings_col2, embeddings_col3, embeddings_col4], axis=1)

# 예측 대상 데이터
target_data = df1['leadtime'].values

# 학습 데이터와 테스트 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(X, target_data, test_size=0.2, random_state=42)

# 훈련 데이터와 검증 데이터로 분할
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)

# 입력 데이터의 형태를 맞추기
X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])
X_val = X_val.reshape(X_val.shape[0], 1, X_val.shape[1])
# X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 400))
# X_val = np.reshape(X_val, (X_val.shape[0], X_val.shape[1], 400))


model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(12309, 64), padding='same'))
model.add(Reshape((12309, 64)))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(64))
model.add(Dense(1))



# # 모델 컴파일
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse'])
# # 모델 학습
model.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_val, y_val))
# 모델 요약 출력
model.summary()



Epoch 1/10


ValueError: in user code:

    File "C:\workspace\ShipSupplies\venv\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "C:\workspace\ShipSupplies\venv\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\workspace\ShipSupplies\venv\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "C:\workspace\ShipSupplies\venv\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "C:\workspace\ShipSupplies\venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\workspace\ShipSupplies\venv\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_32" is incompatible with the layer: expected shape=(None, 12309, 64), found shape=(None, 1, 400)


In [218]:
X_train.shape, X_test.shape, X_val.shape, y_train.shape

((12309, 1, 400), (4104, 1, 400), (4104, 1, 400), (12309,))

In [115]:
X.shape

(82068, 100)

In [72]:
import numpy as np
import pandas as pd
from gensim.models import Word2Vec

# 데이터셋 로드
# data = pd.read_csv('data.csv')

# 각 컬럼에 대한 임베딩 모델 학습
embedding_models = {}
columns = ["청구품목", 'key2', '견적화폐' , '발주처']

X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
y = df1['leadtime']

# for column in columns:
#     # 컬럼 데이터를 리스트로 변환
#     column_data = df1[column].tolist()
    
#     # Word2Vec 모델 학습
#     embedding_model = Word2Vec(sentences=column_data, vector_size=100, window=5, min_count=1, workers=4)
    
#     # 학습된 임베딩 모델 저장
#     embedding_models[column] = embedding_model

from sklearn.feature_extraction.text import TfidfVectorizer

for column in columns:
    # 단어 벡터화 객체 생성
    vectorizer = TfidfVectorizer()
    # 문서 집합을 벡터화
    vectorized_data = vectorizer.fit_transform(df1[column])
    # 벡터화된 데이터를 배열로 변환
    vectors = vectorized_data.toarray()
    df1[column] = vectors

# 임베딩된 벡터를 DataFrame의 컬럼에 할당
# for column in columns:
    # 임베딩된 벡터 저장할 빈 리스트
    # embedded_vectors = []
    
    
    # 각 범주에 대해 임베딩된 벡터 추출
#     for category in df1[column]:
#         # 벡터 추출
#         vector = embedding_models[column].wv[category]
#         embedded_vectors.append(vector)
        
#     # 임베딩된 벡터를 DataFrame의 컬럼으로 할당
#     embedded_vectors = np.array(embedded_vectors)
#     for i in range(embedded_vectors.shape[1]):
#         df1[f"{column}_embedded_{i+1}"] = embedded_vectors[:, i]

# 결과 확인
# print(df1.head())
df1

AttributeError: 'float' object has no attribute 'lower'

In [80]:
df1.iloc[:20,:]

청구품목  key2  리드타임  견적화폐  발주처  leadtime
0    0.0   0.0   194   0.0  0.0       194
1    0.0   0.0    59   0.0  0.0        59
2    0.0   0.0    61   0.0  0.0        61
3    0.0   0.0   212   0.0  0.0       212
4    0.0   0.0   220   0.0  0.0       220
5    0.0   0.0    80   0.0  0.0        80
6    0.0   0.0   100   0.0  0.0       100
7    0.0   0.0    13   0.0  0.0        13
8    0.0   0.0   117   0.0  0.0       117
9    0.0   0.0    96   0.0  0.0        96
10   0.0   0.0     2   0.0  0.0         2
11   0.0   0.0   156   0.0  0.0       156
12   0.0   0.0    72   0.0  0.0        72
13   0.0   0.0    25   0.0  0.0        25
14   0.0   0.0    49   0.0  0.0        49
15   0.0   0.0    49   0.0  0.0        49
16   0.0   0.0    49   0.0  0.0        49
17   0.0   0.0    49   0.0  0.0        49
18   0.0   0.0    56   1.0  0.0        56
19   0.0   0.0    48   1.0  0.0        48

In [70]:
embedding_models = {}
columns = ["청구품목", 'key2', '견적화폐' , '발주처']

X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
y = df1['leadtime']

for column in columns:
    # 컬럼 데이터를 리스트로 변환
    column_data = df1[column].tolist()
    # Word2Vec 모델 학습
    embedding_model = Word2Vec(sentences=column_data, vector_size=100, window=5, min_count=1, workers=4)
    # 학습된 임베딩 모델 저장
    embedding_models[column] = embedding_model

# for column, embedding_model in embedding_models.items():
#     print(f"Column: {column}")
#     print(f"Vocabulary size: {len(embedding_model.wv.index_to_key)}")
#     print(f"Vector size: {embedding_model.vector_size}")
#     print()

v = embedding_models['청구품목'].wv.get_vector('WASHER')
v

# 임베딩된 벡터를 DataFrame의 컬럼에 할당
# for column in columns:
    # 임베딩된 벡터 저장할 빈 리스트
    # embedded_vectors = []
    
    # 각 범주에 대해 임베딩된 벡터 추출
    # for category in df1[column]:
        # 벡터 추출
        # vector = embedding_models[column].wv[category]
        # embedded_vectors.append(vector)
# embedded_vectors

KeyError: "Key 'WASHER' not present"

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

# 입력과 출력 데이터 분리
X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
y = df1['leadtime']
columns = ["청구품목", 'key2', '견적화폐' , '발주처']
 
# LabelEncoder를 사용하여 범주형 변수를 정수로 인코딩
label_encoder = LabelEncoder()
for col in X.columns:
    X[col] = label_encoder.fit_transform(X[col])

    
# y # 정규화
from sklearn.preprocessing import StandardScaler

# 정규화할 y 값
y = df1['leadtime']

# StandardScaler 객체 생성
scaler = StandardScaler()

y_normalized = scaler.fit_transform(y.values.reshape(-1, 1))    

# RobustScaler 객체 생성
# from sklearn.preprocessing import RobustScaler
# scaler = RobustScaler()
# 'leadtime' 컬럼에 로버스트 스케일링 적용
# y = np.array(y)
# y = y.reshape((-1, 1))
# y = scaler.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(X, y_normalized, test_size=0.2, random_state=42) # y 정규화 한 y_normalized
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 

# 회귀 모델 구축
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))


C:\Users\peos0\AppData\Local\Temp\ipykernel_17276\4172538190.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = label_encoder.fit_transform(X[col])
C:\Users\peos0\AppData\Local\Temp\ipykernel_17276\4172538190.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = label_encoder.fit_transform(X[col])
C:\Users\peos0\AppData\Local\Temp\ipykernel_17276\4172538190.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_ind

In [23]:
y_test, y_train

(array([[ 0.99154998],
        [ 0.03041752],
        [-0.28517822],
        ...,
        [-1.01678651],
        [-1.08851281],
        [ 0.05910804]]),
 array([[-0.91636968],
        [-0.02696352],
        [-1.03113177],
        ...,
        [-1.07416755],
        [-1.08851281],
        [-0.97375073]]))

In [9]:
# # y # 정규화
# from sklearn.preprocessing import StandardScaler

# # 정규화할 y 값
# y = df1['leadtime']

# # StandardScaler 객체 생성
# scaler = StandardScaler()

# # y 값 정규화
# y_normalized = scaler.fit_transform(y.values.reshape(-1, 1))

# # 정규화된 y 값 출력
# print(y_normalized.shape)
y_train, y_test

(7854     2.564949
 20118    4.317488
 8523     1.609438
 18477    3.610918
 483      4.127134
            ...   
 11284    2.564949
 11964    5.056246
 5390     0.693147
 860      0.000000
 15795    2.197225
 Name: leadtime, Length: 16413, dtype: float64,
 1493     4.983607
 8503     4.369448
 7408     4.043051
 3509     4.691348
 5927     5.398163
            ...   
 17651    3.912023
 9659     4.290459
 13418    1.791759
 8410     0.000000
 16062    4.394449
 Name: leadtime, Length: 4104, dtype: float64)

In [190]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense

# 학습 및 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y_normalized, test_size=0.2, random_state=42)

# 회귀 모델 구축
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

In [24]:
# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')

In [25]:
# 모델 학습
model.fit(X_train, y_train, epochs=15, batch_size=32)

Epoch 1/15
513/513 [==============================] - 1s 886us/step - loss: 156.0526
Epoch 2/15
513/513 [==============================] - 0s 872us/step - loss: 1.7270
Epoch 3/15
513/513 [==============================] - 0s 860us/step - loss: 5.1974
Epoch 4/15
513/513 [==============================] - 0s 867us/step - loss: 2.3596
Epoch 5/15
513/513 [==============================] - 0s 878us/step - loss: 3.5939
Epoch 6/15
513/513 [==============================] - 0s 870us/step - loss: 5.1697
Epoch 7/15
513/513 [==============================] - 0s 868us/step - loss: 7.8091
Epoch 8/15
513/513 [==============================] - 0s 778us/step - loss: 10.9850
Epoch 9/15
513/513 [==============================] - 0s 749us/step - loss: 3.1372
Epoch 10/15
513/513 [==============================] - 0s 720us/step - loss: 6.0239
Epoch 11/15
513/513 [==============================] - 0s 707us/step - loss: 4.2749
Epoch 12/15
513/513 [==============================] - 0s 697us/step - loss: 2.944

In [26]:
# 모델 평가
loss = model.evaluate(X_test, y_test)

129/129 [==============================] - 0s 701us/step - loss: 0.9326


In [27]:
# 예측
predictions = model.predict(X_test)

129/129 [==============================] - 0s 557us/step


In [28]:
y_test, predictions

(array([[ 0.99154998],
        [ 0.03041752],
        [-0.28517822],
        ...,
        [-1.01678651],
        [-1.08851281],
        [ 0.05910804]]),
 array([[-0.14738107],
        [ 0.05807089],
        [-0.02092768],
        ...,
        [-0.23050714],
        [-0.28623605],
        [-0.16581559]], dtype=float32))

In [15]:
y_test = np.exp(y_test)-1
predictions = np.exp(predictions)-1

In [20]:
# type(y_test), type(predictions)#.shape, predictions.shape
y_test = y_test.values
y_test
# for i in range(100):
    # print(f"실제 시간: {y_test[i]}")
# y_test[:]

array([145.,  78.,  56., ...,   5.,   0.,  80.])

In [17]:
# y_test = y_test.values
y_test.shape,predictions.shape

((4104,), (4104, 1))

In [29]:
# 원래 스케일로 되돌리기
y_test = scaler.inverse_transform(y_test)
predictions = scaler.inverse_transform(predictions)

In [30]:
# 정규화된 y 예측 결과 확인
for i in range(100):
    print(f"실제 시간: {y_test[i]}, 예측 시간: {predictions[i][0]}")

실제 시간: [145.], 예측 시간: 65.60575866699219
실제 시간: [78.], 예측 시간: 79.92770385742188
실제 시간: [56.], 예측 시간: 74.4207534790039
실제 시간: [108.], 예측 시간: 74.33167266845703
실제 시간: [220.], 예측 시간: 64.95346069335938
실제 시간: [43.], 예측 시간: 66.66519165039062
실제 시간: [100.], 예측 시간: 55.93476867675781
실제 시간: [156.], 예측 시간: 84.77539825439453
실제 시간: [10.], 예측 시간: 60.72957992553711
실제 시간: [11.], 예측 시간: 48.52303695678711
실제 시간: [195.], 예측 시간: 78.24974060058594
실제 시간: [153.], 예측 시간: 57.413551330566406
실제 시간: [48.], 예측 시간: 74.20349884033203
실제 시간: [15.], 예측 시간: 38.7536506652832
실제 시간: [59.], 예측 시간: 72.19367218017578
실제 시간: [145.], 예측 시간: 86.27708435058594
실제 시간: [21.], 예측 시간: 43.07725143432617
실제 시간: [42.], 예측 시간: 13.28592300415039
실제 시간: [6.], 예측 시간: 67.968994140625
실제 시간: [46.], 예측 시간: 78.2129135131836
실제 시간: [3.], 예측 시간: 53.16653823852539
실제 시간: [132.], 예측 시간: 64.32881164550781
실제 시간: [3.], 예측 시간: 69.50468444824219
실제 시간: [14.], 예측 시간: 63.65364074707031
실제 시간: [370.], 예측 시간: 109.10581970214844
실제 시간: [0.], 예측 시간: 5

In [19]:
y_test, predictions

(1493     145.0
 8503      78.0
 7408      56.0
 3509     108.0
 5927     220.0
          ...  
 17651     49.0
 9659      72.0
 13418      5.0
 8410       0.0
 16062     80.0
 Name: leadtime, Length: 4104, dtype: float64,
 array([[345.21872 ],
        [114.4686  ],
        [213.50435 ],
        ...,
        [ 67.94038 ],
        [146.45747 ],
        [ 55.648376]], dtype=float32))

In [47]:
y_test = scaler.inverse_transform(y_test)
y_test

array([[10183.74756166],
       [ 5513.21547459],
       [ 3979.60792361],
       ...,
       [  424.42678271],
       [   75.87961203],
       [ 5652.63434286]])

In [48]:
predictions =  scaler.inverse_transform(predictions)
predictions

array([[76.028694],
       [76.028694],
       [76.028694],
       ...,
       [76.028694],
       [76.028694],
       [76.028694]], dtype=float32)

In [49]:
# y 예측 결과 확인
for i in range(100):
    print(f"실제 시간: {y_test[i][0]}, 예측 시간: {predictions[i][0]}")

실제 시간: 10183.747561656593, 예측 시간: 76.02869415283203
실제 시간: 5513.215474587314, 예측 시간: 76.02869415283203
실제 시간: 3979.607923609342, 예측 시간: 76.02869415283203
실제 시간: 7604.498498648185, 예측 시간: 76.02869415283203
실제 시간: 15411.95512180877, 예측 시간: 76.02869415283203
실제 시간: 3073.385279849631, 예측 시간: 76.02869415283203
실제 시간: 7046.823025565286, 예측 시간: 76.02869415283203
실제 시간: 10950.55133714558, 예측 시간: 76.02869415283203
실제 시간: 772.9739533826728, 예측 시간: 76.02869415283203
실제 시간: 842.6833875180351, 예측 시간: 76.02869415283203
실제 시간: 13669.219268424713, 예측 시간: 76.02869415283203
실제 시간: 10741.423034739493, 예측 시간: 76.02869415283203
실제 시간: 3421.932450526443, 예측 시간: 76.02869415283203
실제 시간: 1121.5211240594845, 예측 시간: 76.02869415283203
실제 시간: 4188.736226015429, 예측 시간: 76.02869415283203
실제 시간: 10183.747561656593, 예측 시간: 76.02869415283203
실제 시간: 1539.7777288716588, 예측 시간: 76.02869415283203
실제 시간: 3003.6758457142687, 예측 시간: 76.02869415283203
실제 시간: 494.13621684122336, 예측 시간: 76.02869415283203
실제 시간: 3282.51358225571

In [34]:
# 회귀 모델 구축
model2 = Sequential()
model2.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model2.add(Dense(64, activation='relu'))
model2.add(Dense(32, activation='relu'))
model2.add(Dense(1))

In [36]:
# 모델 컴파일
model2.compile(optimizer='adam', loss='mean_squared_error')

In [37]:
# 모델 학습
model2.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
513/513 [==============================] - 1s 799us/step - loss: 5858.5386
Epoch 2/10
513/513 [==============================] - 0s 784us/step - loss: 5266.6533
Epoch 3/10
513/513 [==============================] - 0s 801us/step - loss: 5078.9551
Epoch 4/10
513/513 [==============================] - 0s 786us/step - loss: 4954.1279
Epoch 5/10
513/513 [==============================] - 0s 787us/step - loss: 4926.1978
Epoch 6/10
513/513 [==============================] - 0s 784us/step - loss: 4866.7661
Epoch 7/10
513/513 [==============================] - 0s 784us/step - loss: 4877.1812
Epoch 8/10
513/513 [==============================] - 0s 817us/step - loss: 4767.5371
Epoch 9/10
513/513 [==============================] - 0s 814us/step - loss: 4769.4419
Epoch 10/10
513/513 [==============================] - 0s 942us/step - loss: 4767.0117


In [38]:

# 모델 평가
loss = model2.evaluate(X_test, y_test)

129/129 [==============================] - 0s 568us/step - loss: 4720.4844


In [39]:
# 예측
predictions = model.predict(X_test)

129/129 [==============================] - 0s 624us/step


In [41]:
for i in range(len(predictions)):
    # print(f"실제 시간: {y_test.iloc[i]}, 예측 시간: {predictions[i][0]}")

SyntaxError: incomplete input (1878388943.py, line 2)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
X = df1[["청구품목", 'key2', '견적화폐' , '발주처']]
X_encoded = X.copy()
le = LabelEncoder()
for col in X.columns:
    X_encoded[col] = le.fit_transform(X[col])
y = df1["leadtime"]
# X = np.array(X)
# y = np.array(y)
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, random_state=40, shuffle=True, test_size=0.3)

In [16]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten
from sklearn.preprocessing import LabelEncoder


model = Sequential()
model.add(Dense(64, activation='relu', input_dim=4))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

In [17]:
X_encoded

청구품목  key2  견적화폐  발주처
0      4848    18     2   22
1      3692    18     2   22
2      5915    18     2   22
3       696    18     2   22
4      4681    18     2   22
...     ...   ...   ...  ...
20512  2811    20     1   35
20513  2810    20     1   35
20514  4151     5     1   41
20515  1592    20     1   41
20516  4718    20     1   41

[20517 rows x 4 columns]

In [18]:
# 모델 컴파일
model.compile(optimizer='adam', loss='mean_squared_error')


In [21]:
# 모델 학습
model.fit(X_train, y_train, epochs=30, batch_size=20)

Epoch 1/30
719/719 [==============================] - 1s 718us/step - loss: 4570.3857
Epoch 2/30
719/719 [==============================] - 0s 685us/step - loss: 4455.8169
Epoch 3/30
719/719 [==============================] - 0s 684us/step - loss: 4454.7124
Epoch 4/30
719/719 [==============================] - 0s 686us/step - loss: 4419.8271
Epoch 5/30
719/719 [==============================] - 1s 708us/step - loss: 4414.2935
Epoch 6/30
719/719 [==============================] - 1s 786us/step - loss: 4395.2896
Epoch 7/30
719/719 [==============================] - 1s 799us/step - loss: 4435.3975
Epoch 8/30
719/719 [==============================] - 1s 787us/step - loss: 4419.7266
Epoch 9/30
719/719 [==============================] - 1s 812us/step - loss: 4406.4590
Epoch 10/30
719/719 [==============================] - 1s 853us/step - loss: 4388.4800
Epoch 11/30
719/719 [==============================] - 1s 875us/step - loss: 4410.8535
Epoch 12/30
719/719 [==============================]

In [22]:
# 모델 평가
loss = model.evaluate(X_test, y_test)

193/193 [==============================] - 0s 714us/step - loss: 4114.6880


In [23]:
# 예측
predictions = model.predict(X_test)

193/193 [==============================] - 0s 587us/step


In [24]:
predictions

array([[ 36.74128 ],
       [ 92.509026],
       [ 91.80747 ],
       ...,
       [101.08235 ],
       [ 44.686443],
       [ 84.99454 ]], dtype=float32)

In [26]:
# 예측 결과 확인
for i in range(len(predictions)):
    print(f"실제값: {y_test[i]}, 예측값: {predictions[i][0]}")

KeyError: 0

## 기업 회귀 모델

In [2]:
import pandas as pd
from sklearn import preprocessing
df = pd.read_csv('../data/raw_postpro.csv')
df1 = df[["청구품목", 'key2', 'leadtime', '견적화폐' , '발주처']]
df1["leadtime"] = df["leadtime"].astype(int)

C:\Users\SW\AppData\Local\Temp\ipykernel_17900\1378052945.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["leadtime"] = df["leadtime"].astype(int)


In [23]:
df

청구서번호  No.   
0      ELS-BS-ESP-2004002   12  \
1      OCA-BS-ESP-2010004    5   
2      MIR-BS-ESP-2011002  119   
3      BLO-BS-ESP-2003002   16   
4      DEO-BS-ESP-2105008   97   
...                   ...  ...   
20512  BLO-BS-ESP-2006006    1   
20513  BLO-BS-ESP-2004008    1   
20514  ELS-BS-ESP-1908002    2   
20515  BLO-BS-ESP-1906014    2   
20516  BLO-BS-ESP-1906014    3   

                                                 Subject   
0                           NO.1 A/E C18 MAJOR O/H PARTS  \
1                   운전시간 대비 #2 AUX ENG TOP END O/H PARTS   
2          운전시간 대비 #2 AUX ENG(CAT 3512C) MAJOR O/H PARTS   
3                           #1 AUX ENG TOP END O/H PARTS   
4                                        DEO-E-210512-01   
...                                                  ...   
20512  BLO-F-ENGINE-200515-03 BOAT DAVIT CYL 외, AIRCO...   
20513  BLO-F-ENGINE-200403-01 (NAVI DECK CRANE DERRIN...   
20514                                ELS-F-ENG-190628-02   
20515            BLO-F-ENGINE-190617-01 (NET BOAT PARTS)   
20516            BLO-F-ENGINE-190617-01 (NET BOAT PARTS)   

                   Machinery                              Assembly   
0      NO.1 GENERATOR ENGINE               323-6480 LINES GP-FUEL   \
1      NO.2 GENERATOR ENGINE                            GASKET KIT   
2      NO.2 GENERATOR ENGINE             285-8374 MANIFOLD GP-EXH    
3      NO.1 GENERATOR ENGINE                     159-8828 TURBO GP   
4      NO.1 GENERATOR ENGINE             2N4727 INSTRUMNT PANEL GP   
...                      ...                                   ...   
20512            HYD. SYSTEM  5-753-2E_BOAT DAVIT & N.D CRANE LINE   
20513            HYD. SYSTEM  5-753-2E_BOAT DAVIT & N.D CRANE LINE   
20514            6M NET BOAT                       ELECTRIC CLUTCH   
20515            7M NET BOAT        HAND HYDRAULIC STEERING SYSTEM   
20516            7M NET BOAT        HAND HYDRAULIC STEERING SYSTEM   

                                      청구품목                     Part No.1   
0                         SEAL-O-RING-STOR                     7.00E-275  \
1                       OIL COOLER & LINES                     7.00E-275   
2                                   WASHER                     7.00E-275   
3                           BOLT-HIGH TEMP                     7.00E-275   
4                                     SEAL                     7.00E-275   
...                                    ...                           ...   
20512         HYD. CYLINDER_NET BOAT DAVIT            φ150 × φ85 × 695st   
20513  HYD. CYLINDER_N.D CRANE_BOOM_LIFTER          φ160 × φ112 × 1130st   
20514                                PULLY                     Φ305X5V-3   
20515                            CYLINDER            Φ50 x S195 CYLINDER   
20516                SEAL KIT FOR CYLINDER  Φ50 x S195 CYLINDER SEAL KIT   

                       Part No.2                                         key1   
0                              0                                    7.00E-275  \
1                              0                                    7.00E-275   
2                              0                                    7.00E-275   
3                              0                                    7.00E-275   
4                              0                                    7.00E-275   
...                          ...                                          ...   
20512  FF-SE-1CB150BB695ABD-YP2J  φ150 × φ85 × 695stFF-SE-1CB150BB695ABD-YP2J   
20513       S-2CA160A20.6N1130-1     φ160 × φ112 × 1130stS-2CA160A20.6N1130-1   
20514                          0                                    Φ305X5V-3   
20515                          0                          Φ50 x S195 CYLINDER   
20516                          0                 Φ50 x S195 CYLINDER SEAL KIT   

           key2  ...  Control No.  입고창고        창고출고  창고출고수량 출고선박   
0        COOLER  ...        혜인 발주    BS  2020-09-19       1  BLO  \
1        COOLER  ...       

In [22]:
df1

청구품목      key2  leadtime 견적화폐   
0                         SEAL-O-RING-STOR    COOLER       194  KRW  \
1                       OIL COOLER & LINES    COOLER        59  KRW   
2                                   WASHER    COOLER        61  KRW   
3                           BOLT-HIGH TEMP    COOLER       212  KRW   
4                                     SEAL    COOLER       220  KRW   
...                                    ...       ...       ...  ...   
20512         HYD. CYLINDER_NET BOAT DAVIT  CYLINDER        95  JPY   
20513  HYD. CYLINDER_N.D CRANE_BOOM_LIFTER  CYLINDER        67  JPY   
20514                                PULLY      BELT        25  JPY   
20515                            CYLINDER   CYLINDER        25  JPY   
20516                SEAL KIT FOR CYLINDER  CYLINDER        25  JPY   

                                    발주처  
0              HAEIN Coporation_Cheonan  
1              HAEIN Coporation_Cheonan  
2              HAEIN Coporation_Cheonan  
3              HAEIN Coporation_Cheonan  
4              HAEIN Coporation_Cheonan  
...                                 ...  
20512          MARINE HYDROTEC CO.,LTD.  
20513          MARINE HYDROTEC CO.,LTD.  
20514  PORT RELIEF ENGINEERING CO.,LTD.  
20515  PORT RELIEF ENGINEERING CO.,LTD.  
20516  PORT RELIEF ENGINEERING CO.,LTD.  

[20517 rows x 5 columns]

In [127]:
from gensim.models import FastText
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = list(df["Subject"]+ ' ' + df['key2']  + ' '   + df['Assembly'] + ' '  + df['출고운반선']+  ' ' + df['견적화폐']  +  ' ' + df['발주처']  )
# type(y[0])
# # y # 정규화
from sklearn.preprocessing import StandardScaler

# target 값
y = df['leadtime']

# StandardScaler 객체 생성
scaler = StandardScaler()

# y
# y 값 정규화
y_normalized = scaler.fit_transform(y.values.reshape(-1, 1))

# 정규화된 y 값 출력
# y_normalized = list(y_normalized)
# y_normalized

# y_normalized
# print(y_normalized.shape)
# y_train, y_test


In [110]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X)

# X_train, X_test, y_train, y_test = train_test_split(X, y_normalized, test_size=0.2, random_state=40) # y 정규화 된 데이터 사용
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40) # 그냥 y 정규화 하지 않고 사용

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE", mse)
print("R2", r2)


MSE 0.21601980646473634
R2 0.7780977070223671


In [80]:
type(y_test),type(y_pred)#.shape

(pandas.core.series.Series, numpy.ndarray)

In [122]:
# X

In [241]:
from gensim.models import FastText
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = list(df["Subject"]+ ' ' + df['key2']  + ' '   + df['Assembly'] + ' '  + df['출고운반선']+  ' ' + df['견적화폐']  +  ' ' + df['발주처']  )

# y # 정규화
from sklearn.preprocessing import StandardScaler
# target 값
y = df['leadtime']

In [242]:
from keras.models import Sequential
from keras.layers import Embedding,LSTM, Conv1D, MaxPooling1D, Dense, Flatten
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# 텍스트 데이터를 정수 시퀀스로 변환
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)


# 시퀀스 패딩
max_sequence_length = 100  # 적절한 시퀀스 길이로 설정
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length)

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, y, test_size=0.2, random_state=42)

# y_train과 y_test 정규화
scaler = StandardScaler()
y_train = scaler.fit_transform(y_train.values.reshape(-1, 1))
y_test = scaler.transform(y_test.values.reshape(-1, 1))


# 모델 구성
# model = Sequential()
# model.add(Embedding(input_dim=500, output_dim=100, input_length=max_sequence_length))
# model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
# model.add(MaxPooling1D(pool_size=2))
# model.add(LSTM(64))
# model.add(Dense(1))

# # 위에 코드 가져옴
# model = Sequential()
# model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(max_sequence_length,)))
# model.add(Reshape((12309, 64)))
# model.add(MaxPooling1D(pool_size=2))
# model.add(LSTM(64))
# model.add(Dense(1))

# 모델 구성
model = Sequential()
model.add(Embedding(input_dim=12309, output_dim=100, input_length=max_sequence_length))
model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(64))
model.add(Dense(1))


# 모델 컴파일
model.compile(loss='mean_squared_error', optimizer='adam')

In [237]:
X_train.shape, y_train.shape
# len(X), len(y)

((16413, 100), (16413, 1))

In [238]:
X_test.shape, y_test.shape

((4104, 100), (4104, 1))

In [243]:
# 모델 훈련
model.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))

Epoch 1/10
165/165 [==============================] - 9s 48ms/step - loss: 0.4121 - val_loss: 0.2166
Epoch 2/10
165/165 [==============================] - 7s 45ms/step - loss: 0.1594 - val_loss: 0.1652
Epoch 3/10
165/165 [==============================] - 7s 45ms/step - loss: 0.1081 - val_loss: 0.1378
Epoch 4/10
165/165 [==============================] - 7s 45ms/step - loss: 0.0767 - val_loss: 0.1183
Epoch 5/10
165/165 [==============================] - 8s 45ms/step - loss: 0.0564 - val_loss: 0.1088
Epoch 6/10
165/165 [==============================] - 7s 45ms/step - loss: 0.0483 - val_loss: 0.0909
Epoch 7/10
165/165 [==============================] - 7s 45ms/step - loss: 0.0430 - val_loss: 0.0915
Epoch 8/10
165/165 [==============================] - 7s 45ms/step - loss: 0.0379 - val_loss: 0.0926
Epoch 9/10
165/165 [==============================] - 7s 45ms/step - loss: 0.0314 - val_loss: 0.0933
Epoch 10/10
165/165 [==============================] - 7s 45ms/step - loss: 0.0271 - val_lo

In [250]:
y_pred = model.predict(X_test)

# 예측 결과 출력
print("Predicted values:")
print(y_pred)

print("Actual values:")
print(y_test)

129/129 [==============================] - 1s 4ms/step
Predicted values:
[[ 0.8787939 ]
 [-0.03099362]
 [-0.32525623]
 ...
 [ 0.03005731]
 [-1.1227385 ]
 [ 0.09150735]]
Actual values:
[[145.]
 [ 78.]
 [ 56.]
 ...
 [  5.]
 [  0.]
 [ 80.]]


In [251]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R^2 Score:", r2)

R^2 Score: -1.170233379217025


In [248]:
# y_test와 y_pred를 numpy 배열로 변환합니다.
# 정규화 하지 않은 데이터
y_test_arr = np.array(y_test)
y_pred_arr = np.array(y_pred)

# 값들을 비교하면서 출력합니다.
for i in range(50):
    print("Actual:", y_test_arr[i], "Predicted:", y_pred_arr[i])

Actual: [145.] Predicted: [137.254]
Actual: [78.] Predicted: [73.74152]
Actual: [56.] Predicted: [53.198986]
Actual: [108.] Predicted: [128.79097]
Actual: [220.] Predicted: [187.18962]
Actual: [43.] Predicted: [46.800457]
Actual: [100.] Predicted: [88.934784]
Actual: [156.] Predicted: [161.49066]
Actual: [10.] Predicted: [8.983459]
Actual: [11.] Predicted: [10.035362]
Actual: [195.] Predicted: [200.47772]
Actual: [153.] Predicted: [169.86134]
Actual: [48.] Predicted: [18.613747]
Actual: [15.] Predicted: [13.10841]
Actual: [59.] Predicted: [73.91463]
Actual: [145.] Predicted: [132.04257]
Actual: [21.] Predicted: [20.742588]
Actual: [42.] Predicted: [40.93881]
Actual: [6.] Predicted: [6.1796494]
Actual: [46.] Predicted: [58.963406]
Actual: [3.] Predicted: [6.081856]
Actual: [132.] Predicted: [123.98383]
Actual: [3.] Predicted: [-0.7919541]
Actual: [14.] Predicted: [12.979439]
Actual: [370.] Predicted: [347.8837]
Actual: [0.] Predicted: [14.553131]
Actual: [140.] Predicted: [154.98233]
Ac

In [247]:
# y_test와 y_pred를 numpy 배열로 변환합니다.
# 정규화 한 데이터

# 원래 스케일로 되돌리기
# y_test = scaler.inverse_transform(y_test)
# y_pred = scaler.inverse_transform(y_pred)

# y_test_arr = np.array(y_test)
# y_pred_arr = np.array(y_pred)

# 값들을 비교하면서 출력합니다.
for i in range(40):
    print("Actual:", y_test_arr[i], "Predicted:", y_pred_arr[i])

Actual: [145.] Predicted: [137.254]
Actual: [78.] Predicted: [73.74152]
Actual: [56.] Predicted: [53.198986]
Actual: [108.] Predicted: [128.79097]
Actual: [220.] Predicted: [187.18962]
Actual: [43.] Predicted: [46.800457]
Actual: [100.] Predicted: [88.934784]
Actual: [156.] Predicted: [161.49066]
Actual: [10.] Predicted: [8.983459]
Actual: [11.] Predicted: [10.035362]
Actual: [195.] Predicted: [200.47772]
Actual: [153.] Predicted: [169.86134]
Actual: [48.] Predicted: [18.613747]
Actual: [15.] Predicted: [13.10841]
Actual: [59.] Predicted: [73.91463]
Actual: [145.] Predicted: [132.04257]
Actual: [21.] Predicted: [20.742588]
Actual: [42.] Predicted: [40.93881]
Actual: [6.] Predicted: [6.1796494]
Actual: [46.] Predicted: [58.963406]
Actual: [3.] Predicted: [6.081856]
Actual: [132.] Predicted: [123.98383]
Actual: [3.] Predicted: [-0.7919541]
Actual: [14.] Predicted: [12.979439]
Actual: [370.] Predicted: [347.8837]
Actual: [0.] Predicted: [14.553131]
Actual: [140.] Predicted: [154.98233]
Ac

In [253]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R^2 Score:", r2)

R^2 Score: -1.170233379217025


In [252]:
mse = model.evaluate(X_test, y_test)
print("Mean Squared Error:", mse)

129/129 [==============================] - 1s 4ms/step - loss: 10423.9658
Mean Squared Error: 10423.9658203125
